version: '3'

services:
    maestro-web:
        image: abiosoft/caddy
        restart: always
        stdin_open: true
        tty: true
        ports:
            - 80:80
        links:
            - maestro-backend
        volumes:
            - ./caddy/Caddyfile:/etc/Caddyfile
            - caddy_data:/etc/caddycerts
            - ../../src:/var/www/maestro
            - ../../logs/caddy:/var/log/caddy
            - ../../logs/api:/var/log/api
        environment:
            CADDYPATH: /etc/caddycerts
            MAESTRO_DEBUG: 1
            # MAESTRO_API_HOST: 127.0.0.1
            # MAESTRO_API_PORT: 3308
            # MAESTRO_API_NAME: maestro
            # MAESTRO_API_USERNAME: maestro
            # MAESTRO_API_PASSWORD:
        networks:
            - default

    maestro-backend:
        image: node:alpine
        command: node /maestro/backend/server.js
        restart: always
        ports:
            - 3308:3308
        links:
            - mongo-db
        volumes:
            - ../../src/backend:/maestro/backend
            - ../../node_modules:/maestro/node_modules
            - ../../logs/parse:/maestro/logs/parse
        environment:
            PORT: 3308
            PARSE_SERVER_APPLICATION_ID: maestro
            PARSE_SERVER_MASTER_KEY: orange
            PARSE_SERVER_DATABASE_URI: mongodb://mongo-db:27017/dev
            PARSE_SERVER_URL: http://maestro.dev/parse
            PARSE_SERVER_LOGS_FOLDER: /maestro/logs/parse
            VERBOSE: 1

    mongo-db:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - database_data:/data/db
            # - ../../data/db:/docker-entrypoint-initdb.d/db

volumes:
    caddy_data:
    database_data:
